name: cardano-mainnet

services:
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:10.1.4
    container_name: cardano-node
    restart: unless-stopped
    environment:
      - CARDANO_NODE_SOCKET_PATH=/opt/cardano/ipc/socket
    networks:
      - dependencies_main-net
    ports:
      - 3001:3001
      - 12798:12798
    volumes:
      - ./cardano-node/mainnet:/config
      - cardano-node-mainnet-ipc:/opt/cardano/ipc
      - cardano-node-mainnet-data:/opt/cardano/data
      - cardano-node-mainnet-db:/data/db
    command:
      run
      --topology /config/topology.json
      --host-addr 0.0.0.0
      --port 3001
      --config /config/config.json

volumes:
  cardano-node-mainnet-data:
  cardano-node-mainnet-ipc:
  cardano-node-mainnet-db:

networks:
  dependencies_main-net:
    driver: bridge
    external: true
