name = "aiken-laboratory/first-test"
version = "0.0.0"
compiler = "v1.1.12"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-laboratory/first-test'"

[repository]
user = "aiken-laboratory"
project = "first-test"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
